class_name Species extends Resource

@export var id: int
@export var name: String
@export var order: int
@export var genus: String
@export var flavor: String
@export var gender_rate: int
@export var capture_rate: int
@export var base_happiness: int
@export var is_baby: bool
@export var is_legendary: bool
@export var is_mythical: bool
@export var hatch_counter: int
@export var has_gender_differences: bool
@export var forms_switchable: bool
@export var growth_rate: GrowthRate
@export var local_dex: int
@export var national_dex: int
@export var egg_groups: Array
@export var evolution_chain: int
@export var habitat: String
